### ISSUE TITLE
IAB helper not set up exception

### ISSUE THREAD

**Issue by aeroperf** [PrivacyApps/donations#15]
Occasionally I get the following exception while using the library:

java.lang.IllegalStateException: IAB helper is not set up. Can't perform operation: launchPurchaseFlow
    at org.sufficientlysecure.donations.google.util.IabHelper.checkSetupDone(IabHelper.java:781)
    at org.sufficientlysecure.donations.google.util.IabHelper.launchPurchaseFlow(IabHelper.java:371)
    at org.sufficientlysecure.donations.DonationsFragment.donateGoogleOnClick(DonationsFragment.java:345)
    at org.sufficientlysecure.donations.DonationsFragment$1.onClick(DonationsFragment.java:218)
    at android.view.View.performClick(View.java:4439)
    at android.widget.Button.performClick(Button.java:148)
    at android.view.View$PerformClick.run(View.java:18395)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:176)
    at android.app.ActivityThread.main(ActivityThread.java:5319)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by Javinator9889** [comment]
I am getting this error again, and it happens in non-Lollipop devices. It is impossible for me to catch it and manage the exception. Here is the stack track trace:
`FATAL EXCEPTION: ControllerMessenger
Process: javinator9889.bitcoinpools, PID: 8409
java.lang.IllegalStateException: IAB helper is not set up. Can't perform operation: launchPurchaseFlow
	at org.sufficientlysecure.donations.google.util.IabHelper.checkSetupDone(IabHelper.java:784)
	at org.sufficientlysecure.donations.google.util.IabHelper.launchPurchaseFlow(IabHelper.java:374)
	at org.sufficientlysecure.donations.DonationsFragment.donateGoogleOnClick(DonationsFragment.java:350)
	at org.sufficientlysecure.donations.DonationsFragment$1.onClick(DonationsFragment.java:226)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24697)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:465)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:421)
	at android.support.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:235)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:140)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:123)
	at android.support.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
	at android.support.test.espresso.action.Tap.access$100(Tap.java:31)
	at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:47)
	at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:136)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:355)
	at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:242)
	at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by dschuermann** [comment]
@Javinator9889 Please open a new issue and make sure you use the latest version.
